// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMWlHUJm8BvpNX68GxICU2j8T-Fg86TGo',
    appId: '1:765585247584:web:8da84805300b5493e7a205',
    messagingSenderId: '765585247584',
    projectId: 'timetrack-264b6',
    authDomain: 'timetrack-264b6.firebaseapp.com',
    storageBucket: 'timetrack-264b6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD10LJbObH4BnGJxVVrcjwxGgL42poi5fQ',
    appId: '1:765585247584:android:567556e9a2073b82e7a205',
    messagingSenderId: '765585247584',
    projectId: 'timetrack-264b6',
    storageBucket: 'timetrack-264b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4Mp94gMxMzKFBVFZWX4Ug1Sqe3M8M-ng',
    appId: '1:765585247584:ios:d14cb62eaf6251c2e7a205',
    messagingSenderId: '765585247584',
    projectId: 'timetrack-264b6',
    storageBucket: 'timetrack-264b6.firebasestorage.app',
    iosBundleId: 'com.example.timetrack',
  );
}
